name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit

  docker-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: Install Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

      - name: Build Docker image
        run: docker build -t soundboard-tracker .

      - name: Run Docker Scout
        run: |
          docker scout quickview soundboard-tracker
          docker scout cves soundboard-tracker --format sarif --output scout-results.sarif
          echo "Checking for Critical and High severity vulnerabilities..."
          docker scout cves soundboard-tracker | grep -E "CRITICAL|HIGH" || echo "No Critical or High severity vulnerabilities found." 